# Values used for the deployed application.
replicaCount: 2
service:
  name: upp-next-video-annotations-mapper
env:
  APP_NAME: "Next Video Annotations Mapper"
  APP_SYSTEM_CODE: up-nvam
  APP_PORT: 8080
  PANIC_GUIDE: https://runbooks.in.ft.com/up-nvam
  Q_GROUP: videoAnnotationsMapper
  Q_READ_TOPIC: NativeCmsMetadataPublicationEvents
  Q_WRITE_TOPIC: ConceptAnnotations
